= Reference-tr

Reference-tr, ** Türkçe ** olarak Arduino sözdiziminin Language Reference belgelerinin repoudur.  
Tüm Referans terimleri dosyaları AsciiDoc formatındadır.

Arduino içeriğine katkıda bulunmak için zaman ayırdığınız için teşekkür ederiz, bu gerçekten tüm Arduino Topluluğu için faydalıdır. Bu projeye katkıda bulunma konusunda daha fazla bilgi edinmek istiyorsanız, lütfen https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37 adresini ziyaret edin[adım adım öğretici bu adım].

== İçerik Oluşturma ve Düzenleme
Yeni içeriğe katkıda bulunmak istiyorsanız, yeni bir dosya oluşturun (herhangi bir metin veya kod düzenleyiciyle) ve .adoc olarak kaydedin..  
Dosya adında parantez veya özel bir karakter kullanmayın. 
https://raw.githubusercontent.com/arduino/reference-tr/master/AsciiDoc_sample/AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary.adoc [`reference-tr / AsciiDoc_sample / AsciiDoc_Dictionary`de size bir genel bakış bulacaksınız. Bu, Başlıklar, Metin, Bağlantılar, Resimler, Tablolar, Kod ve çeşitli yerleştirmeleri (video, slayt gösterisi, ses ve kod) içerir. Bunun için https://www.arduino.cc/reference/en/asciidoc_sample/asciidoc_dictionary/asciidoc_template-dictionary/CLhere] yazdığını görebilirsiniz.

Dil Referansına katkıda bulunmak veya mevcut içeriği düzenlemek istiyorsanız, reference-tr / AsciiDoc_sample / Reference_Terms'de iki şablon bulabilirsiniz:

* https://raw.githubusercontent.com/arduino/reference-tr/master/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Single_Entity.adoc [] AsciiDoc_Template-Single_Entity.adoc`] kullanın (https://www.edre.edoc.edoc.emoc.emoc.emoc.emoc.emoc_doc.emoc/ / tr / asciidoc_sample / reference_terms / asciidoc_template-single_entity / [here]) link gibi terimler için: http: //arduino.cc/en/Reference/AnalogWrite [analogWrite].
* 
391/5000
https://raw.githubusercontent.com/arduino/reference-tr/master/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Parent_Of_Entities.adoc [`AsciiDoc_Template-Parent_Of_Entities.adoc`] (hale https://www.arduino.cc/reference kullanın / tr / asciidoc_sample / reference_terms / asciidoc_template-parent_of_entities / [here]) link gibi fonksiyon grupları için: http: //arduino.cc/en/Reference/Serial [Serial].

Lütfen her Referans dosyasının en az bir Açıklama, bazı Örnek Kod ve diğer ilgili bilgilerle bağlantılar içermesi gerektiğini unutmayın (Ayrıca bakınız) 



Asciidoc'a resim eklemeniz gerekirse, lütfen Asciidoc dosyasıyla aynı dizinde ekler adı verilen bir klasör oluşturun. Görüntüler SVG ve PNG formatında, maksimum 200 KB boyutunda kaydedilebilir.
== Github'daki İçeriğe Katkıda Bulun
Git'e aşina değilseniz, çevrimiçi arayüzleri üzerinden doğrudan Github'daki içeriğe katkıda bulunabilirsiniz. Size nasıl yapıldığını göstermek için kısa bir Öğretici hazırladık, https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37[BUNA BİR BAK!].

link: https: //help.github.com/articles/editing-files-in-another-user-s-repository/ [Bu kılavuzu takip edebilirsiniz] (Github ekibi tarafından yazılmıştır) adoc dosyasını ve Arduino ekibine bir dosya değişikliği önerin.  
Bir değişiklik önerirken, lütfen Referans şablon dosyalarında açıklanan talimatları izleyin.


== Bir çekme isteği gönderme
Arduino Referansına katkıda bulunmak istediğinize sevindik: topluluğa yardım etmenin en iyi yolu bu.

Katkınız, mevcut kod veya tam açıklamaları eklemek veya değiştirmek, lütfen katkıda bulunmadan önce daima mevcut bir konuya bakın veya yeni bir tane açın. 

=== Klasör Yapısı
[source]
----
reference-tr
├─ AsciiDoc_sample
│   ├── AsciiDoc_Dictionary
│   │   ├── AsciiDoc_Template-Dictionary.adoc
│   │   └── attachments
│   └── Reference_Terms
│       ├── AsciiDoc_Template-Parent_Of_Entities.adoc
│       ├── AsciiDoc_Template-Single_Entity.adoc
│       └── attachments
├── Language
│   ├── Functions
│   ├── Structure
│   └── Variables
├── LICENCE.md
└── README.adoc

----

Langauge klasörü içindeki dosya ağacı, bağlantıdakiyle aynı yapıyı izler: https: //www.arduino.cc/reference/tr[Arduino Referans web sayfası]

=== Lisans

Lütfen, Arduino Referansına yaptığınız katkıların, bir Creative Commons Atıf-Benzer Hem Hisse Senedi 3.0 Lisansı altında lisanslandığını unutmayın. bkz. https://creativecommons.org/licenses/by-sa/3.0/

Creative Commons lisansi, basligi = "Creative Commons License"] Bu eser bir bağlantı altında lisanslanmıştır: https: // creativecommons. org / lisans / yan sa / 3.0 / deed.en[Creative Commons Attribution-ShareAlike 3.0 Desteklenmeyen Lisans].
