---
Başlık: Varlık Veli Başlığı
kategoriler: [ "Fonksiyonlar" ]
Alt kategoriler: [ "Alt kategori adı" ]
---
// ARDUINO DİL REFERANS ETİKETİ (yukarıda)   ►►►►► HER ZAMAN DOSYADA DAHİL ◄◄◄◄◄
//Başlık tüm Referans terimler Dizininde
// Kategoriler: Yapı, Değişken veya İşlev arasında seçim yapma
// Dizinde bulunanlar içindeki alt kategori ("Dijital Giriş / Çıkış", "Aritmetik Operatörler")





// SAYFA BAŞLIĞI   ►►►►► BU ZORUNLU ◄◄◄◄◄
= Kurumların Ebeveynliği title()


// GENEL BAKIŞ
[#genelbakış]
--

[float]
=== Description
// Bu Referans terimleri grubunun ne için kullanıldığını açıklayınız, - BU BÖLÜM ZORUNLU -
Arduino kartı ile bir bilgisayar veya diğer cihazlar arasındaki haberleşmede kullanılır. Tüm Arduino kartlarının en az bir seri portu vardır (UART veya USART olarak da bilinir): Seri. Dijital pinler 0 (RX) ve 1 (TX) ile bilgisayar üzerinden USB üzerinden haberleşir. Bu nedenle, eğer bu işlevleri kullanırsanız, dijital giriş veya çıkış için 0 ve 1 pimlerini de kullanamazsınız. +
Arduino kartıyla iletişim kurmak için Arduino ortamının yerleşik seri monitörünü kullanabilirsiniz. Araç çubuğundaki seri monitör düğmesine tıklayın ve çağrıda kullanılan baud oranını `başlar ()` ile seçin.
[% Hardbreaks]
* Arduino Mega * 'nın üç ek seri bağlantı noktası vardır: 19 ve R (Pin)' de Seri 1 've 18 (TX)' de, 17 (RX) ve 16 'da (Seri 3), 15 ve 15 (RX)' de Seri 3 ' ve 14 (TX). Bu pinleri kişisel bilgisayarınızla iletişim kurmak için kullanmak için, Mega'nın USB-seri adaptörüne bağlı olmadıkları için ek bir USB-seri adaptöre ihtiyacınız olacaktır. Bunları harici bir TTL seri cihazla iletişim kurmak için kullanmak için, TX pimini cihazınızın RX pimine, RX'i cihazınızın TX pimine ve Mega'nızın zemini cihazınızın toprağına bağlayın. (Bu pinleri doğrudan RS232 seri portuna bağlamayın; +/- 12V'de çalışırlar ve Arduino kartınıza zarar verebilir.)
[% Hardbreaks]
* Arduino DUE *, üç adet ek 3.3V TTL seri bağlantı noktasına sahiptir: 19 (RX) ve 18 (TX) pinlerinde `Seri1 '; 17 (RX) ve 16 (TX) pinlerinde Seri2, 15 (RX) ve 14 (TX) pinlerinde Seri3. 0 ve 1 pinleri ayrıca USB hata ayıklama portuna bağlı olan ATmega16U2 USB-TTL Seri yongasının karşılık gelen pinlerine de bağlanır. Ek olarak, SAM3X yongası SerialUSB'de yerel bir USB seri bağlantı noktası vardır.
[% Hardbreaks]
* Arduino Leonardo * kartı, 0 (RX) ve 1 (TX) pinlerindeki TTL (5V) seri üzerinden iletişim kurmak için Seri 1'i kullanır. “Seri”, USB CDC iletişimi için ayrılmıştır. Daha fazla bilgi için, Leonardo'nun başlangıç sayfasına ve donanım sayfasına bakın.
--
// GENEL BAKIŞ




// FONKSİYONLAR BÖLÜM BAŞLADI
[#fonksiyonlar]
--

'''

[float]
=== Functions
// Bu Başvuru üst öğesindeki tüm işlevleri listeleyin. ►►►►► BU BÖLÜM ZORUNLU ◄◄◄◄◄
http://arduino.cc[if] (Serial) +
http://arduino.cc[available()] +
http://arduino.cc[begin()] +
http://arduino.cc[end()] +
http://arduino.cc[find()] +
http://arduino.cc[findUntil()] +
http://arduino.cc[flush()] +
http://arduino.cc[parseFloat()] +
http://arduino.cc[parseInt()] +
http://arduino.cc[peek()] +
http://arduino.cc[print()] +
http://arduino.cc[println()] +
http://arduino.cc[read()] +
http://arduino.cc[readBytes()] +
http://arduino.cc[readBytesUntil()] +
http://arduino.cc[setTimeout()] +
http://arduino.cc[write()] +
http://arduino.cc[serialEvent()]

'''

--
// FONKSİYONLAR BÖLÜMÜ SONU


// BİRLİKTE BAŞLAYIN
[#Ayrıcabakınız]
--

[float]
=== Ayrıca bakınız
// İlgili içeriği diğer Referans terimleri gibi kategorilere göre bağlayın (lütfen # LANGUAGE # etiketini ekleyin),
// tanımları (lütfen # TANIM # etiketini ekleyin) ve Projeler ve Öğreticilerden örnekler
// (lütfen # EXAMPLE # etiketini ekleyin)  ►►►►► BU BÖLÜM ZORUNLU ◄◄◄◄◄


[rol="language"]
// Bir başka Referans terimine veya genel olarak göreli bir bağlantıya bağlanmak istediğinizde,
// aşağıda gösterilen sözdizimini kullanın. Lütfen dosya formatının özellik ile değiştirildiğini unutmayın.
// Klasör / dosya adlarında bulabileceğiniz boşlukları her zaman% 20 ile değiştirmeniz gerektiğini lütfen unutmayın
// Referans sayfalara olan bağlantının tamamı, bu havuzdaki klasör ve dosyaların durumuna bakılmaksızın küçük olmalıdır.
* # LANGUAGE # link: ../ AsciiDoc_Template-Single_Entity [Tek Birlik]
* # LANGUAGE # link: ../../ AsciiDoc_Dictionary / AsciiDoc_Template-Sözlük [AsciiDoc Şablon Sözlük]

[rol="definition"]
// Son köşeli parantezlerin hemen önüne ^ ekleyerek tüm harici bağlantıların yeni bir pencerede / sekmede açılması gerektiğini lütfen unutmayın.
* # TANIM # http://arduino.cc/en/Tutorial/PWMMLPWM^]

[rol="example"]
// Son köşeli parantezlerin hemen önüne ^ ekleyerek tüm harici bağlantıların yeni bir pencerede / sekmede açılması gerektiğini lütfen unutmayın.
* # ÖRNEK # http://arduino.cc/en/Tutorial/BlinkLEXBlink^]

--
// BİLEŞEN BÖLÜM SONU GÖR
